CREATE SCHEMA IF NOT EXISTS environ;

GRANT USAGE ON SCHEMA environ TO alexuser;

DROP TABLE IF EXISTS environ.caroccupancysample CASCADE;

CREATE TAble environ.caroccupancysample (
	id serial,--zip5_vshp varchar(5) ,
	occupants SMALLINT,
-- 	Name	text,
-- 	Team	varchar(14),
-- 	Longitude	float(13),
-- 	Latitude float(13)
	access_point text
)
;


INSERT INTO environ.caroccupancysample (occupants, access_point)
VALUES
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(3, 'Neyland Drive'),
	(6, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(3, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(5, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(1, 'Neyland Drive'),
	(6, 'Neyland Drive'),
	(3, 'Neyland Drive'),
	(6, 'Neyland Drive'),
	(3, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(1, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(3, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(1, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(1, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(3, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(6, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(3, 'Neyland Drive'),
	(3, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(3, 'Neyland Drive'),
	(3, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(3, 'Neyland Drive'),
	(1, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(5, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(5, 'Neyland Drive'),
	(1, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(1, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(3, 'Neyland Drive'),
	(1, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(3, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(3, 'Neyland Drive'),
	(3, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(1, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(1, 'Neyland Drive'),
	(3, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(1, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(3, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(1, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(3, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(5, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(3, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(1, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(3, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(3, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(1, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(1, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(4, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(3, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Neyland Drive'),
	(2, 'Phillip Fulmer Way'),
	(2, 'Phillip Fulmer Way'),
	(4, 'Phillip Fulmer Way'),
	(2, 'Phillip Fulmer Way'),
	(4, 'Phillip Fulmer Way'),
	(2, 'Phillip Fulmer Way'),
	(4, 'Phillip Fulmer Way'),
	(4, 'Phillip Fulmer Way'),
	(1, 'Phillip Fulmer Way'),
	(5, 'Phillip Fulmer Way'),
	(5, 'Phillip Fulmer Way'),
	(3, 'Phillip Fulmer Way'),
	(5, 'Phillip Fulmer Way'),
	(4, 'Phillip Fulmer Way'),
	(2, 'Phillip Fulmer Way'),
	(4, 'Phillip Fulmer Way'),
	(2, 'Phillip Fulmer Way'),
	(2, 'Phillip Fulmer Way'),
	(3, 'Phillip Fulmer Way'),
	(2, 'Phillip Fulmer Way'),
	(4, 'Phillip Fulmer Way'),
	(3, 'Phillip Fulmer Way'),
	(2, 'Phillip Fulmer Way'),
	(4, 'Phillip Fulmer Way'),
	(2, 'Phillip Fulmer Way'),
	(2, 'Phillip Fulmer Way'),
	(3, 'Phillip Fulmer Way'),
	(4, 'Phillip Fulmer Way'),
	(2, 'Phillip Fulmer Way'),
	(4, 'Phillip Fulmer Way'),
	(2, 'Phillip Fulmer Way'),
	(2, 'Phillip Fulmer Way'),
	(3, 'Phillip Fulmer Way'),
	(4, 'Phillip Fulmer Way'),
	(2, 'Phillip Fulmer Way'),
	(4, 'Phillip Fulmer Way')
;

GRANT SELECT ON ALL TABLES IN SCHEMA skratch, adminareas, tickets, ehc_sec, environ TO alexuser;
